#### 1. Import the numpy package under the name `np` (★☆☆)

In [123]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [124]:
a = np.zeros(10)  # Create an array of all zeros
print(a, "\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [125]:
a = np.zeros(10)
print(a, "\n")


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



In [126]:
a[5] = 1 #upate the fifth value as 1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [127]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [128]:
a = np.arange(0, 9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [129]:
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)


#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye

In [130]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [131]:
c = np.random.random((3,3,3))
print(c)

[[[0.05476701 0.63996359 0.34013065]
  [0.52192869 0.3654113  0.58210118]
  [0.81347076 0.41071209 0.69240338]]

 [[0.94751906 0.26901849 0.36979723]
  [0.23601084 0.33574366 0.70514631]
  [0.28507425 0.76559695 0.7054547 ]]

 [[0.04900636 0.27965437 0.75148077]
  [0.18177386 0.18144433 0.45426069]
  [0.8114716  0.9169548  0.16114137]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [132]:
c = np.random.random((10,10))
print(c)

[[0.00857197 0.2791335  0.83162667 0.59846257 0.84624989 0.03555602
  0.50113744 0.46483085 0.00118682 0.72035353]
 [0.58492748 0.69265364 0.52001012 0.92269951 0.87014497 0.99775889
  0.27379685 0.34903343 0.08707151 0.17291558]
 [0.87456473 0.87336254 0.15600163 0.99269711 0.50752698 0.5280645
  0.03584059 0.26725238 0.75781354 0.53623951]
 [0.11059383 0.24345075 0.31699133 0.6929198  0.40147975 0.17631544
  0.22072598 0.56839101 0.4092596  0.70048002]
 [0.43079864 0.43850863 0.31144395 0.35387104 0.92613018 0.0121665
  0.51484614 0.32589414 0.96684478 0.90822686]
 [0.19100269 0.09298887 0.17316032 0.46735528 0.30594566 0.65698411
  0.63909974 0.14580816 0.51876863 0.12620942]
 [0.76350741 0.07589881 0.88485304 0.41526214 0.91239862 0.71477477
  0.09334183 0.76311809 0.06403925 0.22907808]
 [0.80834327 0.07837666 0.06260471 0.59470121 0.66752585 0.71499161
  0.24695991 0.54851405 0.84328342 0.55840044]
 [0.81911301 0.7442846  0.79004952 0.03796407 0.70445277 0.00130124
  0.02958104 0

In [133]:
c.min()

0.0011868207670876485

In [134]:
c.max()

0.9977588914309773

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [135]:
x = np.random.random((30))
print(x)

[0.79444197 0.70364945 0.24672392 0.30860056 0.77106394 0.05094552
 0.25399206 0.76888101 0.60803027 0.64288755 0.91595092 0.42206928
 0.77979883 0.98848919 0.90450899 0.182458   0.39636681 0.01022942
 0.99345378 0.36956809 0.30871188 0.6247218  0.95024504 0.39141216
 0.07518851 0.22189981 0.17912493 0.17693834 0.3424649  0.12457483]


In [137]:
x.size

30

In [138]:
x.mean()

0.4835797254318027

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [139]:
a=np.diag(np.arange(1,5),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [140]:
x = np.random.random((5,5))

In [141]:
print(x)

[[0.21495659 0.88858093 0.37985265 0.87074493 0.9860103 ]
 [0.97232827 0.10445891 0.56539665 0.96851702 0.28031651]
 [0.50108985 0.47286977 0.94998769 0.93945356 0.59624992]
 [0.45695548 0.93494732 0.12619694 0.79938518 0.74686081]
 [0.59930336 0.8678764  0.80818954 0.445031   0.94817074]]


In [142]:
x.mean()

0.6569492133039394

In [143]:
std = np.std(x)

In [144]:
std

0.28192906340559853

In [145]:
normalize=x-x.mean()/std

In [146]:
print(normalize)

[[-2.11523671 -1.44161236 -1.95034064 -1.45944836 -1.34418299]
 [-1.35786502 -2.22573438 -1.76479664 -1.36167628 -2.04987679]
 [-1.82910345 -1.85732353 -1.38020561 -1.39073974 -1.73394338]
 [-1.87323781 -1.39524597 -2.20399636 -1.53080812 -1.58333249]
 [-1.73088993 -1.46231689 -1.52200376 -1.88516229 -1.38202255]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [147]:
x = [2, 6, 1, 3, 4]
y = [2, 3, 1, 6, 7,]

In [148]:
np.intersect1d(x,y)

array([1, 2, 3, 6])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [149]:
x = np.random.random((10))

In [150]:
x

array([0.68172653, 0.32998125, 0.6646482 , 0.2906304 , 0.51885868,
       0.293053  , 0.34487834, 0.56430075, 0.90076765, 0.98031021])

In [151]:
x.sort()

In [152]:
x

array([0.2906304 , 0.293053  , 0.32998125, 0.34487834, 0.51885868,
       0.56430075, 0.6646482 , 0.68172653, 0.90076765, 0.98031021])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [153]:
x = np.random.random((10))

In [154]:
x

array([0.64709798, 0.23110316, 0.33219012, 0.58218523, 0.67181437,
       0.1633406 , 0.20682077, 0.39360171, 0.67869623, 0.06523298])

In [155]:
x[x.argmax()]=0

In [157]:
x

array([0.64709798, 0.23110316, 0.33219012, 0.58218523, 0.67181437,
       0.1633406 , 0.20682077, 0.39360171, 0.        , 0.06523298])

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [158]:
a = np.random.rand(3, 4)
print(a)

[[0.13637746 0.61965123 0.51707921 0.6845142 ]
 [0.67584014 0.58924882 0.3510857  0.19938163]
 [0.2049628  0.51005626 0.72634184 0.89961341]]


In [170]:
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[ 0.41790573 -0.2761079  -0.14179783]
 [-0.25371693  0.32301826 -0.06930133]
 [ 0.07894351 -0.11979454  0.04085103]
 [ 0.02830064 -0.04917534  0.0208747 ]
 [-0.31793409  0.46144924 -0.14351515]]


#### 17. How to get the n largest values of an array

In [160]:
z = np.arange(10000)
z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [161]:
np.random.shuffle(z)
n=5

In [162]:
print (z[np.argsort(z)[-n:]])

[9995 9996 9997 9998 9999]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares

In [163]:
a = np.random.random((5,3))
print(a)

[[0.7719893  0.07797566 0.21228573]
 [0.26326934 0.84000453 0.44768495]
 [0.76185926 0.56312121 0.72376678]
 [0.3053982  0.22792221 0.29797226]
 [0.0906041  0.86998743 0.26502303]]


In [164]:
b=np.where(a > 4,a,a**2)
    

In [165]:
print(b)

[[0.59596748 0.0060802  0.04506523]
 [0.06931075 0.70560762 0.20042182]
 [0.58042954 0.31710549 0.52383835]
 [0.09326806 0.05194854 0.08878747]
 [0.0082091  0.75687812 0.07023721]]
